name: New Device

on:
  issues:
    types: [opened, edited]

jobs:
  create-device-pull-request:
    if: ${{ contains(github.event.issue.labels.*.name, 'new-device') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Parse device data
        id: device-data
        uses: issue-ops/parser@v5
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: new_device_request.yaml

      - name: Install jq
        run: sudo apt install jq

      - name: Set up python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Update JSON file
        id: update-json
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import re
            import json

            # Load the existing JSON library file
            with open("library/library.json",'r') as f:
              devices_json = json.loads(f.read())
              devices = devices_json.get('devices')

            # Remove the "battery_quantity" key from the device dictionary if it's 1
            new_device = ${{ steps.device-data.outputs.json }}
            # Convert battery_quantity field to a numeric
            numeric_quantity = int(new_device["battery_quantity"])
            del new_device["battery_quantity"]
            # Add  numeric "battery_quantity" key if it's more than 1
            if numeric_quantity > 1:
              new_device["battery_quantity"] = numeric_quantity
            if new_device.get("model_id", "MISSING").strip() == "":
              del new_device["model_id"]
            if new_device.get("hw_version", "MISSING").strip() == "":
              del new_device["hw_version"]

            # Fix common typo in battery type
            if new_device.get("battery_type", "").lower() == "rechargable":
              new_device["battery_type"] = "Rechargeable"

            # Check for duplicates and replace old entry with new one, flagging manual entries
            duplicate_found = False
            manual_found = False
            for i, device in enumerate(devices):
              if device["manufacturer"] == new_device["manufacturer"] and device["model"] == new_device["model"] and device.get("model_id", "") == new_device.get("model_id", "") and device.get("hw_version", "") == new_device.get("hw_version", ""):
                if device["battery_type"].upper() == "MANUAL":
                  manual_found = True
                  break
                devices[i] = new_device
                duplicate_found = True
                break

            # If no duplicate found and not currently manual, add the new device to the JSON library file
            if not duplicate_found and not manual_found:
              devices.append(new_device)

            # Save manufacturer and model for later use
            set_env("BRANCH", "_".join(re.findall(r"\w+",f"{new_device['manufacturer']} {new_device['model']} {new_device.get('model_id', '')} {new_device.get('hw_version', '')})".lower())))
            set_env("MANUFACTURER", new_device['manufacturer'])
            set_env("MODEL", new_device['model'])
            set_env("MODEL_ID", new_device.get('model_id', ''))
            set_env("HW_VERSION", new_device.get('hw_version', ''))
            set_env("BQT", f"{numeric_quantity}x {new_device['battery_type']}")

            if duplicate_found:
              set_env("MODE", "updates")
              set_env("TITLE_MODE", "Update")
            else:
              set_env("MODE", "adds")
              set_env("TITLE_MODE", "Add")

            set_env("MANUAL", str(manual_found))

            if not manual_found:
              with open("library/library.json", "w") as f:
                f.write(json.dumps(devices_json, indent=4))

      - name: Rename Issue
        run: |
          curl --request PATCH \
            --url https://api.github.com/repos/${{github.repository}}/issues/${{github.event.issue.number}} \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
              "title": "Device: ${{ env.MANUFACTURER }} - ${{ env.MODEL }}"
            }'

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        if: "${{ env.MANUAL != 'True' }}"
        env:
          INPUT_SCHEMA: library/schema.json
          INPUT_JSONS: library/library.json

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        if: "${{ env.MANUAL != 'True' }}"
        with:
          commit-message: "${{ env.TITLE_MODE }} device: ${{ env.MODEL }} by ${{ env.MANUFACTURER }}"
          title: "${{ env.TITLE_MODE }} device: ${{ env.MANUFACTURER }} - ${{ env.MODEL }}"
          body: |
            This pull request ${{ env.MODE }} the device information for:
            Manufacturer: ${{ env.MANUFACTURER }}
            Model: ${{ env.MODEL }}
            Model ID: ${{ env.MODEL_ID }}
            Hardware: ${{ env.HW_VERSION }}
            Battery: ${{ env.BQT }}
            It closes issue #${{ github.event.issue.number }}

            If Battery Notes is useful to you please
            [!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/codechimp)
          branch: "device-${{ env.BRANCH }}"

      - name: Close Issue
        run: gh issue close --comment "$BODY" ${{github.event.issue.number}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: >
            Thanks for the contribution. We're auto-closing this issue. If it's a new device, a pull request will be created that will be reviewed and merged.


            If Battery Notes is useful to you please


            [!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/codechimp)
